apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: monitoring-api
  template:
    metadata:
      labels:
        app: monitoring-api
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: monitoring-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
