apiVersion: v1
kind: Service
metadata:
  name: monitoring-api-service
spec:
  selector:
    app: monitoring-api
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: {{ .Values.service.type }}
